# Base URL for your site (used for links and assets)
base_url = https://abed-kotob.github.io/jemdoc_mathjax/

# Path to MathJax library; you can use CDN or local copy
mathjax_url = https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-AMS_HTML

# Optional: specify the TeX delimiters
mathjax_inline = ["$","$"]
mathjax_block = [["\\[","\\]"]]